version: '3.8'
services:
    app:
        env_file: .env
        networks:
            - bridge_net
    memcached:
        image: memcached:alpine
        restart: always
        env_file: .env
        networks:
            - bridge_net
#       ports:
#           - "11211:11211"
networks:
    bridge_net:
        driver: bridge